require '/Users/saritaradia/Desktop/Projects/Golden-Square/lib/Phase-Two-Skill-Challenges/03_Design_A_Single_Method/Exercise_One_User_Time.rb/exercise_one_user_time.rb'

RSpec.describe "reading_time method" do 
    it "returns an empty string if given an empty string" do 
        expect(reading_time("")).to eq ""
    end 

    it "returns the string time when string is not empty" do
        result = reading_time("One Two Three Four Five Six Seven Eight Nine Ten Eleven Twelve Thirteen Fourteen Fifteen")
        expect(result).to eq "0.0 minutes"
    end 

    it "If the string length equal to or less than 199 words, return 0.0" do
        result = reading_time("Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string")
        expect(result).to eq "0.0 minutes"
    end 

    it "returns 1 if the string is between 200 - 400 words" do 
        result = reading_time("Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string")
        expect(result).to eq "1.0 minute"
    end 

    it "returns 2 if the string is between 400 - 600 words" do 
        result = reading_time("Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string  Test this long repetitive string  Test this long repetitive string Test this long repetitive string")
        expect(result).to eq "2.0 minutes" 
    end 
end 